# These are supported funding model platforms

github: [Jovisx]
patreon: # Replace with a single Patreon username
open_collective: [Jovisx]
ko_fi: Jovis
tidelift: # Replace with a single Tidelift platform-name/package-name e.g., npm/babel
custom: # Replace with a single custom sponsorship URL
